apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tripviewer
  namespace: api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: tripviewer.52.185.228.232.nip.io
    http:
      paths:
      - backend:
          serviceName: trips
          servicePort: 80
        path: /api/trips
      - backend:
          serviceName: poi
          servicePort: 80
        path: /api/poi
      - backend:
          serviceName: user-java
          servicePort: 80
        path: /api/user-java
      - backend:
          serviceName: userprofile
          servicePort: 80
        path: /api/user