apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tripviewer
  namespace: web
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: tripviewer.52.185.228.232.nip.io
    http:
      paths:
      - backend:
          serviceName: tripviewer
          servicePort: 80
        path: /