apiVersion: v1
kind: Service
metadata:
  name: userprofile
spec:
  selector:
    app: userprofile
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: userprofile
spec:
    selector:
        matchLabels:
            app: userprofile
    replicas: 2
    template:
        metadata:
            labels: {app: userprofile}
        spec:
            containers: [{name: userprofile, image: 'registry6y44587.azurecr.io/hacker2/userprofile:1.0', imagePullPolicy: Always, env: [{name: SQL_USER, value: sqladmin6Y44587}, {name: SQL_PASSWORD, value: 6C4sw7Ol4}, {name: SQL_SERVER, value: sqlserver6y44587.database.windows.net}, {name: SQL_DBNAME, value: mydrivingDB}], ports: [{containerPort: 80}]}]

