apiVersion: v1
kind: Service
metadata:
  name: user-java
  namespace: api
spec:
  selector:
    app: user-java
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api
spec:
  selector:
      matchLabels:
        app: user-java
  replicas: 2
  template:
      metadata:
        labels:
            app: user-java
      spec:
        containers:
        - name: user-java
          image: registry6y44587.azurecr.io/hacker3/user-java:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: test
              mountPath: /secrets
              readOnly: true
          env: 
            - name: PORT
              value: "80"
            - name: SQL_SERVER
              value: "sqlserver6y44587.database.windows.net"
            - name: SQL_DBNAME
              value: "mydrivingDB"
        volumes:
        - name: test
          flexVolume:
              driver: "azure/kv"
              secretRef:
                name: kvcreds
              options:
                usepodidentity: "false"
                keyvaultname: aksProd-kv
                keyvaultobjectnames: "sql--password;sql--user"
                keyvaultobjectaliases: "SQL_PASSWORD;SQL_USER" # Name of Key Vault secret
                keyvaultobjecttypes: "secret;secret"
                resourcegroup: teamResources
                subscriptionid: 75159368-bf37-41f2-86ee-725899d35f50
                tenantid: a24b3d45-7d4d-43b6-8310-d4574595ca1e